onlyBuiltDependencies:   # pnpm 10
  - "@parcel/watcher"
  - better-sqlite3
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp
allowBuilds:             # pnpm 11
  "@parcel/watcher": true
  better-sqlite3: true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  gatsby: true
  gatsby-cli: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
